version: '3.8'

services:
  auth:
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8081:8081"

  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: auth_service
      PGDATA: /var/lib/postgresql/data/auth_service
    volumes:
      - auth_pg_data:/var/lib/postgresql/data/auth_data
    ports:
      - "5432:5432"

volumes:
  auth_pg_data: